name: Merge AI Rules

on:
  schedule:
    - cron: "0 0 * * *" # 每天0点执行一次（UTC时间），可根据需要调整
  workflow_dispatch:

permissions:
  contents: write # 赋予写权限以允许 push 操作
  actions: read

jobs:
  merge-rules:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set timezone to Asia/Shanghai
        run: |
          echo "Setting timezone to Asia/Shanghai"
          sudo timedatectl set-timezone Asia/Shanghai
          timedatectl

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch Rules Files
        run: |
          mkdir rules
          cp CustomRules.yaml rules/
          curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Gemini/Gemini.yaml" -o rules/Gemini.yaml
          curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OpenAI/OpenAI.yaml" -o rules/OpenAI.yaml
          curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Claude/Claude.yaml" -o rules/Claude.yaml

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install PyYAML
        run: |
          pip install pyyaml

      - name: Merge Rules with Comments
        run: |
          python merge_rules.py

      - name: Check if changes
        run: |
          git diff --quiet ai-rules.yaml || echo "Changes detected"

      - name: Commit and Push if changes
        run: |
          git add ai-rules.yaml
          git commit -m "chore: update ai规则集 at $(date '+%Y-%m-%d %H:%M:%S')"
          git push -v --progress

